### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by MehmetcanTozlu** [instantX-research/CSGO#14]
Hi,
When I run infer_CSGO.py in default settings, I get the following error:

RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for latents: copying a param with shape torch.Size([1, 16, 2048]) from checkpoint, the shape in current model is torch.Size([1, 32, 2048]).

It works when I make num_style_tokens=16. But this time the image is distorted.

**Comment by BBBoundary** [comment]
Hi! I have met the same problem! Could you tell me how to solve it? thanks!!

**Comment by ChiehYunChen** [comment]
Hey, I encounter the same error and change the CSGO loading model from csgo.bin to **csgo_4_32.bin** solve the issue
