### ISSUE TITLE
Question about Dataset Size and Typo in the Paper

### ISSUE THREAD

**Issue by MingKunLei** [instantX-research/CSGO#2]
I have a question regarding the dataset mentioned in your paper. You mentioned selecting 11,000 content images and 10,000 style images, but the resulting dataset consists of only 210k pairs instead of 110 million (11,000 x 10,000). Could you please clarify why this is the case?

Additionally, I noticed that on page six of the paper, the word "style" is spelled as "styl". I wanted to bring this to your attention.

Thank you for your time and for your great work on this research.

**Comment by xingp-ng** [comment]
> I have a question regarding the dataset mentioned in your paper. You mentioned selecting 11,000 content images and 10,000 style images, but the resulting dataset consists of only 210k pairs instead of 110 million (11,000 x 10,000). Could you please clarify why this is the case?
> 
> Additionally, I noticed that on page six of the paper, the word "style" is spelled as "styl". I wanted to bring this to your attention.
> 
> Thank you for your time and for your great work on this research.

Image generation is time- and resource-consuming, and can theoretically yield 110 million data. However, due to lack of resources and time, we have only constructed 210k data so far.

We verified the validity of CSGO on 210k data triples.

Typo has been fixed, thanks for your attention.

**Comment by MingKunLei** [comment]
> > I have a question regarding the dataset mentioned in your paper. You mentioned selecting 11,000 content images and 10,000 style images, but the resulting dataset consists of only 210k pairs instead of 110 million (11,000 x 10,000). Could you please clarify why this is the case?
> > Additionally, I noticed that on page six of the paper, the word "style" is spelled as "styl". I wanted to bring this to your attention.
> > Thank you for your time and for your great work on this research.
> 
> Image generation is time- and resource-consuming, and can theoretically yield 110 million data. However, due to lack of resources and time, we have only constructed 210k data so far.
> 
> We verified the validity of CSGO on 210k data triples.
> 
> Typo has been fixed, thanks for your attention.

Thank you for your response and clarification!

**Comment by t00350320** [comment]
can you share some details about resource requirements to let me know if we can support you some V100s or l40s to enhance the model

**Comment by xingp-ng** [comment]
> can you share some details about resource requirements to let me know if we can support you some V100s or l40s to enhance the model
The relevant training resources are mentioned in the paper（we use 8 H800 GPUs）, and we expect to actively develop the FLux_based CSGO model. Unfortunately, resources have been severely lacking recently.
