### ISSUE TITLE
No module named 'ip_adapter'

### ISSUE THREAD

**Issue by sp1cae** [instantX-research/CSGO#6]
python app.py 

Traceback (most recent call last):
  File "/home/im/multi-gpt/CSGO/gradio/app.py", line 6, in <module>
    from ip_adapter.utils import BLOCKS as BLOCKS
ModuleNotFoundError: No module named 'ip_adapter'

**Comment by xingp-ng** [comment]
you can add these code:
import sys
sys.path.append(/path/your dir)
I hope this helps you.
