### ISSUE TITLE
模型下载

### ISSUE THREAD

**Issue by sp1cae** [instantX-research/CSGO#7]
Our method is fully compatible with [SDXL](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0), [VAE](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix), [ControlNet](https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic), and [Image Encoder](https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models/image_encoder). Please download them and place them in the ./base_models folder. 
这一步需要下载哪些具体的模型啊 
 [SDXL](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) 岂不是很大

**Comment by xingp-ng** [comment]
> Our method is fully compatible with [SDXL](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0), [VAE](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix), [ControlNet](https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic), and [Image Encoder](https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models/image_encoder). Please download them and place them in the ./base_models folder. 这一步需要下载哪些具体的模型啊 [SDXL](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) 岂不是很大

All connected models require You can download the weights of the FP16 version.
