### ISSUE TITLE
cannot import name 'BLOCKS' from 'ip_adapter.utils'

### ISSUE THREAD

**Issue by sp1cae** [instantX-research/CSGO#8]
Requirement already satisfied: ip_adapter in /home/im/miniforge3/envs/CSGO/lib/python3.9/site-packages (0.1.0)

**Comment by xingp-ng** [comment]
same with issue#6

**Comment by xingp-ng** [comment]
same with [#6](https://github.com/instantX-research/CSGO/issues/6)
