### ISSUE TITLE
Release dataset

### ISSUE THREAD

**Issue by zhirfang** [instantX-research/CSGO#9]
Thank you very much for your work. I would like to ask when the dataset will be made publicly available?

**Comment by zhirfang** [comment]
Additionally, while reproducing the code, I encountered the following error when loading the IP-adapter:
size mismatch for latents: copying a param with shape torch.Size([1, 16, 2048]) from checkpoint, the shape in current model is torch.Size([1, 32, 2048]).
May I ask which type of IP-adapter is being used？

**Comment by xingp-ng** [comment]
> Additionally, while reproducing the code, I encountered the following error when loading the IP-adapter: size mismatch for latents: copying a param with shape torch.Size([1, 16, 2048]) from checkpoint, the shape in current model is torch.Size([1, 32, 2048]). May I ask which type of IP-adapter is being used？

if you use csgo_4_32.bin, style_token=32 is right. if you use csgo.bin  style_token should be revised to 16

**Comment by zhirfang** [comment]
> > Additionally, while reproducing the code, I encountered the following error when loading the IP-adapter: size mismatch for latents: copying a param with shape torch.Size([1, 16, 2048]) from checkpoint, the shape in current model is torch.Size([1, 32, 2048]). May I ask which type of IP-adapter is being used？
> 
> if you use csgo_4_32.bin, style_token=32 is right. if you use csgo.bin style_token should be revised to 16

Thank you very much.
